plugins:
  dart_exception_lint:
    path: ..
    diagnostics:
      no_null_assertion: true
      no_manual_throw: true
      catch_throwing_third_party_calls: true
      catch_runtime_throw_sources: true
      catch_async_error_sources: true
      catch_inferred_throwing_calls: true
      catch_unknown_dynamic_calls: true
    exception_analysis:
      strictness:
        internal: possible
        third_party: deliberate
